name: Documentation

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"
      - name: Install package
        run: pip install -e .
      - name: Install Sphinx dependencies
        working-directory: docs
        run: pip install -r requirements.txt
      - name: Convert README.md to reStructuredText
        uses: docker://pandoc/core:3.1-alpine
        with:
          args: --from=markdown --to=rst --output=docs/README.rst README.md
      - name: Sphinx build
        working-directory: docs
        run: sphinx-build . _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          publish_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true